.MODEL SMALL
.STACK 100H
.DATA 
    INPUT_MSG DB 'ENTER YOUR NUMBER: $'
    NUM DB 0D
    OUTPUT_MSG DB 0DH,0AH,'Factorial IS: $'
    FACT DB 0D
    I DB 1D
.CODE
;description
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    MOV ES,AX

    ;SHOW INPUT PROMPT MSG
    MOV AH,9D
    LEA DX,INPUT_MSG
    INT 21H

    ;TAKE INPUT
    MOV AH,1
    INT 21H
    SUB AL,48D
    CMP AL,0D ;Exceptional case 0! = 1
    JE EXCEPTION_CASE_FOR_ZERO
    MOV I,AL

    FACTORIAL:
        DEC I
        CMP I,0D
        JLE PRINT_FACTORIAL

        MUL I
    JMP FACTORIAL

    EXCEPTION_CASE_FOR_ZERO:
        MOV AL,1D

    PRINT_FACTORIAL:

    ;STORE THE VALUE FROM AL
    MOV FACT, AL
    ADD FACT,48D
    ;SHOW OUTPUT MSG PROMPT
    MOV AH,9D
    LEA DX, OUTPUT_MSG
    INT 21H

    MOV DL,FACT
    MOV AH,2
    INT 21H

    MOV AH,4CH
    INT 21H
MAIN ENDP
END MAIN