.MODEL SMALL
.STACK 100H
.DATA
    PROMPT_MSG_FOR_INPUT DB 'ENTER YOUR NUMBER: $'
    EVEN_MSG DB 0DH,0AH,'EVEN NUMBER$'
    ODD_MSG DB 0DH,0AH,'ODD NUMBER$'
    NUM DW 0D
    REMAINDER DB 0D
    QUOTIENT DB 0D
    DIVIDEND DB 2D
.CODE
;description
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    MOV ES,AX

    ;SHOW PROMPT MSG
    MOV AH,09D
    LEA DX,PROMPT_MSG_FOR_INPUT
    INT 21H

    ;TAKE INPUT
    MOV AH,1D
    INT 21H
    SUB AL,48D
    
    ;CHECK EVEN OR ODD
    DIV DIVIDEND
    CMP AH,0D
    JE EVEN
    JMP ODD

    EVEN:
    LEA DX,EVEN_MSG
    MOV AH,9
    INT 21H
    JMP EXIT

    ODD:
    LEA DX,ODD_MSG
    MOV AH,9
    INT 21H
    EXIT:
    ;EXIT DOS
    MOV AH,4CH
    INT 21H
MAIN ENDP
END MAIN